### ISSUE TITLE
Emoji Logic Deprecation Warning

### ISSUE THREAD

**Issue by BalzaniEdoardo** [smarie/mkdocs-gallery#103]
Hi, thanks for the awesome package!

mkdcos-material is raising a deprecation warning:

```
          Material emoji logic has been officially moved into mkdocs-material
          version 9.4. Please use Material's 'material.extensions.emoji.twemoji'
          instead of 'materialx.emoji.twemoji' in your 'mkdocs.yml' file.
          
           ```
           markdown_extensions:
             - pymdownx.emoji:
                 emoji_index: !!python/name:material.extensions.emoji.twemoji
                 emoji_generator: !!python/name:material.extensions.emoji.to_svg
           ```
```

However in the `src/mkdocs-gallery/plugin.py`, the deprecated configuration is set, line 226-228 of that script.

This result in a warning when building the docs.

Replacing those lines with,

```yml
- pymdownx.emoji:
                 emoji_index: !!python/name:material.extensions.emoji.twemoji
                 emoji_generator: !!python/name:material.extensions.emoji.to_svg
```

would fix the warning. Is there a reason you did not update the config yet?

Best regards,
Edoardo
