### ISSUE TITLE
Incompatibility with `mkdocs-jupyter`

### ISSUE THREAD

**Issue by smarie** [smarie/mkdocs-gallery#51]
It seems that using both plugins at the same time leads to files not being detected by `mkdocs-jupyter`.

```yaml
nav:
    - Home: index.md
    - Experiments: generated/gallery
    - Experiments Nb:
        - My Test: gallery_nb\experiment.ipynb

theme: material  # readthedocs  mkdocs

plugins:
  - gallery:
      examples_dirs: docs/gallery          # path to your example scripts
      gallery_dirs: docs/generated/gallery  # where to save generated gallery
      filename_pattern: ".*"
      within_subsection_order: FileNameSortKey  # order according to file name
  - mkdocs-jupyter:
      execute: False
      include: ["*.ipynb"]
      ignore: ["generated/gallery/*.ipynb"]
```
