### ISSUE TITLE
Find some way to configure `reset-argv` and the like using a python script

### ISSUE THREAD

**Issue by smarie** [smarie/mkdocs-gallery#9]
Since we only have `mkdocs.yml` users can not provide python objects to the config.

However several config options do require that users pass a class (custom or not).

It would be good to allow users to specify in mkdocs.yml a path to a python file. For example

```yaml
plugins:
  - gallery:
      conf_py: docs/gallery_conf.py
```
