### ISSUE TITLE
Defining page setup in README.md

### ISSUE THREAD

**Issue by schlegelp** [smarie/mkdocs-gallery#96]
Hi! I've been trying to use the page setup (title, icon, etc) in the gallery's `README.md` as described [here](https://squidfunk.github.io/mkdocs-material/reference/#customization):

`examples/README.md`
```markdown
---
title: test
icon: material/help-circle
---

## General Tutorials

These are some general introductory tutorials:
```

Strangely, `mkdocs` then renders it like this:
<img width="1095" alt="Screenshot 2024-09-04 at 09 13 09" src="https://github.com/user-attachments/assets/45c26c17-b8ae-4d88-b52c-a2d9cda2f9c7">

This is the `nav` config:

```yml
nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Tutorials: generated/gallery
  ...
```

The `/generated/gallery/index.md` looks like this:
```markdown
<!-- docs_generated_gallery -->

---
title: test
icon: material/help-circle
---

# General Tutorials

These are some general introductory tutorials:

<div class ....
```

Any idea? I played around with changing the navigation, removing headings, etc. but to no avail. I appreciate that this may well be an issue with mkdocs or mkdocs material but I thought I'd ask here first.

Thanks!

PS: Love this library - made my life so much easier!
